# Generated by Django 3.1.2 on 2021-01-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_kaarpuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroles',
            options={'verbose_name': 'User Roles', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterField(
            model_name='kaarpuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userroles'),
        ),
    ]
