# Generated by Django 3.1.2 on 2021-01-28 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='datetime_of_creation',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='datetime_of_updation',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_of_updation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_of_creation',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_of_updation',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
